name: s_time
description: A Flutter package for s_time functionality
issue_tracker: https://github.com/SoundSliced/s_time/issues
repository: https://github.com/SoundSliced/s_time
version: 1.0.0
homepage: https://github.com/SoundSliced/s_time

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_ink_button: ^1.1.0
  soundsliced_dart_extensions: ^1.0.1
  assorted_layout_widgets: ^11.0.0
  s_widgets: ^1.0.1
  keystroke_listener: ^1.0.1
  dart_helper_utils: ^5.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
